services:
  loadbalancer_server:
    image: loadbalancer_server
    ports:
      - 3001:3001

  server1:
    image: server
    container_name: server1
    environment:
      - PORT=30000
    ports:
      - 30000:30000

  server2:
    image: server
    container_name: server2
    environment:
      - PORT=30001
    ports:
      - 30001:30001


  database:
    image: db
    container_name: mysql_server
    ports:
      - 3306:3306